name: Release

on:
  create:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:
  generate:
    name: Release artifacts
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: echo Hello
